<?php

use Illuminate\Support\Facades\Route;

Route::get('/login',[
    App\Http\Controllers\LoginController::class,
    'index'
]);

Route::get('/table',[
    App\Http\Controllers\LoginController::class,
    'table'
]);
Route::get('/layout',[
    App\Http\Controllers\LoginController::class,
    'layout'
]);
Route::get('/employees',[
    App\Http\Controllers\EmployeesController::class,
    'employees'
]);
Route::get('/department',[
    App\Http\Controllers\DepartmentController::class,
    'department'
]);
Route::get('/loans',[
    App\Http\Controllers\LoansController::class,
    'loans'
]);
Route::get('/leaves',[
    App\Http\Controllers\LeavesController::class,
    'leaves'
]);
Route::get('/mandatorydeduction',[
    App\Http\Controllers\MDController::class,
    'mandatorydeduction'
]);
Route::get('/timekeeping',[
    App\Http\Controllers\TKController::class,
    'timekeeping'
]);
Route::get('/payslip',[
    App\Http\Controllers\PayslipController::class,
    'payslip'
]);
Route::get('/form',[
    App\Http\Controllers\LoginController::class,
    'form'
]);
Route::get('/department/create',[
    App\Http\Controllers\LoginController::class,
    'department_create'
]);
Route::get('/employees/create',[
    App\Http\Controllers\LoginController::class,
    'employees_create'
]);
Route::get('/leaves/create',[
    App\Http\Controllers\LoginController::class,
    'leaves_create'
]);
Route::get('/loans/create',[
    App\Http\Controllers\LoginController::class,
    'loans_create'
]);
Route::get('/mandatorydeduction/create',[
    App\Http\Controllers\LoginController::class,
    'MD_create'
]);
Route::get('/timekeeping/create',[
    App\Http\Controllers\LoginController::class,
    'TK_create'
]);
Route::get('/timekeeping/view',[
    App\Http\Controllers\LoginController::class,
    'TK_view'
]);
Route::get('/payslip/create',[
    App\Http\Controllers\LoginController::class,
    'payslip_create'
]);
Route::get('/payslip/view',[
    App\Http\Controllers\LoginController::class,
    'payslip_view'
]);

